### ISSUE TITLE
 Connect-AADAssessment does not work on cloudshell

### ISSUE THREAD

**Issue by cpinotossi** [AzureAD/AzureADAssessment#15]
PS /home/ga> Connect-AADAssessment
Connect-AADAssessment: The 'Connect-AADAssessment' command was found in the module 'AzureADAssessment', but the module could not be loaded. For more information, run 'Import-Module AzureADAssessment'.

**Comment by jasoth** [comment]
The module does not currently import into cloud shell due to a dll conflict with the MSAL.PS module dependency. There is a pull request to the MSAL.PS module that could fix this but I have not had time to publish a new version. Once that is fixed, we can revisit cloud shell support. However, I'm not sure it will ever work due to the large data/memory requirements.
