### ISSUE TITLE
Error: The "guid" property was not found for this object. Make sure that the property is present.

### ISSUE THREAD

**Issue by CW-RKR** [AzureAD/AzureADAssessment#49]
When running Invoke-AADAssessmentDataCollection -OutputDirectory 'C:\Temp\azureadassessment\' I get an error.

Sorry for German. Don't know how to switch Powershell to English output. Deepl translation of this error: "The "guid" property was not found for this object. Make sure that the property is present."

Die Eigenschaft "guid" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die Eigenschaft
vorhanden ist.
In C:\Program
Files\WindowsPowerShell\Modules\AzureADAssessment\2.2.36\Invoke-AADAssessmentDataCollection.ps1:228
Zeichen:9
+         $ReferencedIdCache.roleGroup.guid | Get-MsGraphResults 'group ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : PropertyNotFoundStrict

**Comment by schmarrap** [comment]
Hi,

I've also reported similar combined issue https://github.com/AzureAD/AzureADAssessment/issues/48. It's currently being investigated and I some temp fixes in my fork https://github.com/schmarrap/AzureADAssessment

**Comment by cblomart** [comment]
Hi @schmarrap, @CW-RKR,

We just updated the preview version with f917b59 that should handle no existing "guid" attribute.
https://www.powershellgallery.com/packages/AzureADAssessment/2.2.39-preview

Will follow up on #48 before rolling changes to the master (non-preview module)

Please validate that this is solved before we close this issue.

**Comment by schmarrap** [comment]
> Hi @schmarrap, @CW-RKR,
> 
> We just updated the preview version with [f917b59](https://github.com/AzureAD/AzureADAssessment/commit/f917b59c38921d96ce001a1fcd61e71cf579da3b) that should handle no existing "guid" attribute. https://www.powershellgallery.com/packages/AzureADAssessment/2.2.39-preview
> 
> Will follow up on #48 before rolling changes to the master (non-preview module)
> 
> Please validate that this is solved before we close this issue.

Hi, 

I done testing with preview feature, Invoke-AADAssessmentDataCollection reported no errors. 
![image](https://user-images.githubusercontent.com/8980059/171985647-01060536-bd4b-4dd6-8185-a988a5b597d8.png)

But, Complete-AADAssessmentReports reported Warning:
![image](https://user-images.githubusercontent.com/8980059/171985671-7ea4d018-11a2-4aaa-940a-06c7ccb97b35.png)

Running PowerBI still gives error:
![image](https://user-images.githubusercontent.com/8980059/171985957-7b9ee669-2ff0-4659-a80b-927c3313153e.png)

Refreshed ApplicationPermission and apply filter:
![image](https://user-images.githubusercontent.com/8980059/171986018-c7abcbf8-4e9a-43b6-a870-e76f36ba21f5.png)

Didn't see any issues in query:
![image](https://user-images.githubusercontent.com/8980059/171986048-b6d1f9fc-38a7-4f3a-9cec-d599f606fa92.png)

Then PowerBI Worked. guess PowerBI issues ?

![image](https://user-images.githubusercontent.com/8980059/171986084-3fafd809-40cf-4153-8a92-d69683db31cd.png)

Conditional Access PowerBI file not found:
![image](https://user-images.githubusercontent.com/8980059/171986143-577e7aa3-df25-4088-96d2-a2c2e7d8acf0.png)

I copy RoleAssignmentReport.csv file and rename it to roleAssignments.csv
![image](https://user-images.githubusercontent.com/8980059/171986208-d3d301e6-8fbb-4594-976d-3a54d6b81b8e.png)

MemberType not found in csv file for users
![image](https://user-images.githubusercontent.com/8980059/171986246-99250d85-5a2e-4606-b8e8-4800902ebf58.png)

![image](https://user-images.githubusercontent.com/8980059/171986380-3e3e64e8-be83-4d56-ba9c-85e198abfd87.png)

builtin not found
![image](https://user-images.githubusercontent.com/8980059/171986397-8723f65a-30ac-431f-a8f6-0edcd92574af.png)

More columns in csv file
![image](https://user-images.githubusercontent.com/8980059/171986432-68afe587-beb1-450d-ab14-17b518b6f15e.png)
Still a few things that needs to be fixed with conditional access rules.

**Comment by cblomart** [comment]
Thanks @schmarrap.
I'll take a look at the conditional access dashboard and the complete-aadassessmentreports.
Cédric

**Comment by cblomart** [comment]
Closing as guid per se is not an issue any more - following on #48
